version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  scraper:
    build: .
    depends_on:
      - db
    env_file: .env
    # Run only once per 'up', on build this will be cron scheduled :)
    command: ["python", "scraper.py"]

volumes:
  db_data: